#!/bin/bash

# Setup parameters
memory=100
data=1000
tmp_rootdir=/var/tmp/
tmp_subdir=speed-test/
tmp_fulldir=$tmp_rootdir$tmp_subdir

# Helper methods
function reset_dir {
	rm -rf $tmp_fulldir
	mkdir $tmp_fulldir
}

function compile_results {
	tar -czf $1 results1.tab results2.tab results3.tab output1.txt output2.txt output3.txt
	rm results1.tab results2.tab results3.tab output1.txt output2.txt output3.txt
}

# Compilation of TPIE
if [ "$1" != "faster" ]; then
	# Compile TPIE Master
	cd tpie-master/build
	cmake -DCMAKE_BUILD_TYPE=Release ..
	make -j9 tpie
	cd ../..
fi

if [ "$1" != "master" ]; then
	# Compile TPIE Faster
	cd tpie-faster/build
	cmake -DCMAKE_BUILD_TYPE=Release ..
	make -j9 tpie
	cd ../..
fi

# Compilation of sort_test
make -j9

# Run
if [ "$1" != "faster" ]; then
	echo "--- MASTER SORTING ---"
	for i in {1..3}
	do
		reset_dir
		TMPDIR=$tmp_fulldir ./bin/master results${i}.tab $data $memory |& tee output${i}.txt;
		echo
		echo
	done

	compile_results master.tar.gz
fi

if [ "$1" != "master" ]; then
	echo "--- EVEN-FASTER-SORTING ---";
	for i in {1..3}
	do
		reset_dir
		TMPDIR=$tmp_fulldir ./bin/faster results${i}.tab $data $memory |& tee output${i}.txt;
		echo
		echo
	done

	compile_results faster.tar.gz
fi
